import {CategoryT, verbsT, Words} from "@/types/verbs-types.ts";
import traveling from "@/images/traveling.jpg";
import foods from "@/images/foods.jpg";
import city from "@/images/city_image.jpg"
import home from "@/images/home_interior.jpg"
import people from "@/images/people.jpg"
import freeTime from "@/images/people_free_time.jpg"
import nature from "@/images/nature.jpg"
import language from "@/images/languages,.jpg"
import technology from "@/images/technology.jpg"
import education from "@/images/education_featur.jpg"
import fashion from "@/images/fashion.jpg"
import art from "@/images/art_and_entertainment.jpg"
import health from "@/images/healthy_lifestyle.jpg"
import career from "@/images/career.jpg"

export const verbs: verbsT[] = [
  // A
  // {verb1: "abide", verb2: "abode / abided", verb3: "abode / abided"},
  // {verb1: "arise", verb2: "arose", verb3: "arisen"},
  // {verb1: "awake", verb2: "awoke", verb3: "awaked / awoke"},
  { verb1: "abide", pronunciation1: "[ əˈbaɪd ]", verb2: "abode / abided", pronunciation2: "[ əˈboʊd / əˈbaɪdɪd ]", verb3: "abode / abided", pronunciation3: "[ əˈboʊd / əˈbaɪdɪd ]" },
  { verb1: "arise", pronunciation1: "[ əˈraɪz ]", verb2: "arose", pronunciation2: "[ əˈroʊz ]", verb3: "arisen", pronunciation3: "[ əˈrɪzn ]" },
  { verb1: "awake", pronunciation1: "[ əˈweɪk ]", verb2: "awoke", pronunciation2: "[ əˈwoʊk ]", verb3: "awaked / awoke", pronunciation3: "[ əˈweɪkt / əˈwoʊk ]" },

  // B
  // {verb1: "backbite", verb2: "backbit", verb3: "backbitten"},
  // {verb1: "be", verb2: "was / were", verb3: "been"},
  // {verb1: "bear", verb2: "bore", verb3: "born / borne"},
  // {verb1: "beat", verb2: "beat", verb3: "beaten"},
  // {verb1: "become", verb2: "became", verb3: "become"},
  // {verb1: "begin", verb2: "began", verb3: "begun"},
  // {verb1: "behold", verb2: "beheld", verb3: "beheld"},
  // {verb1: "bend", verb2: "bent", verb3: "bent / bended"},
  // {verb1: "bereave", verb2: "bereft / bereaved", verb3: "bereft / bereaved"},
  // {verb1: "bespeak", verb2: "bespoke", verb3: "bespoke / bespoken"},
  // {verb1: "bet", verb2: "bet / betted", verb3: "bet / betted"},
  // {verb1: "bid", verb2: "bad / bade / bid", verb3: "bid / bidden"},
  // {verb1: "bind", verb2: "bound", verb3: "bound"},
  // {verb1: "bite", verb2: "bit", verb3: "bit / bitten"},
  // {verb1: "bleed", verb2: "bled", verb3: "bled"},
  // {verb1: "bless", verb2: "blessed", verb3: "blessed / blest"},
  // {verb1: "blow", verb2: "blew", verb3: "blown / blowed"},
  // {verb1: "break", verb2: "broke", verb3: "broken"},
  // {verb1: "breed", verb2: "bred", verb3: "bred"},
  // {verb1: "bring", verb2: "brought", verb3: "brought"},
  // {verb1: "broadcast", verb2: "broadcast", verb3: "broadcast"},
  // {verb1: "build", verb2: "built", verb3: "built"},
  // {verb1: "burn", verb2: "burnt / burned", verb3: "burnt / burned"},
  // {verb1: "burst", verb2: "burst", verb3: "burst"},
  // {verb1: "bust", verb2: "bust / busted", verb3: "bust / busted"},
  // {verb1: "buy", verb2: "bought", verb3: "bought"},
  { verb1: "backbite", pronunciation1: "[ ˈbækˌbaɪt ]", verb2: "backbit", pronunciation2: "[ ˈbækˌbɪt ]", verb3: "backbitten", pronunciation3: "[ ˈbækˌbɪtn̩ ]" },
  { verb1: "be", pronunciation1: "[ biː ]", verb2: "was / were", pronunciation2: "[ wɒz / wɜːr ]", verb3: "been", pronunciation3: "[ bɪn ]" },
  { verb1: "bear", pronunciation1: "[ bɛr ]", verb2: "bore", pronunciation2: "[ bɔːr ]", verb3: "born / borne", pronunciation3: "[ bɔːrn ]" },
  { verb1: "beat", pronunciation1: "[ biːt ]", verb2: "beat", pronunciation2: "[ biːt ]", verb3: "beaten", pronunciation3: "[ ˈbiːtn ]" },
  { verb1: "become", pronunciation1: "[ bɪˈkʌm ]", verb2: "became", pronunciation2: "[ bɪˈkeɪm ]", verb3: "become", pronunciation3: "[ bɪˈkʌm ]" },
  { verb1: "begin", pronunciation1: "[ bɪˈɡɪn ]", verb2: "began", pronunciation2: "[ bɪˈɡæn ]", verb3: "begun", pronunciation3: "[ bɪˈɡʌn ]" },
  { verb1: "behold", pronunciation1: "[ bɪˈhoʊld ]", verb2: "beheld", pronunciation2: "[ bɪˈhɛld ]", verb3: "beheld", pronunciation3: "[ bɪˈhɛld ]" },
  { verb1: "bend", pronunciation1: "[ bɛnd ]", verb2: "bent", pronunciation2: "[ bɛnt ]", verb3: "bent / bended", pronunciation3: "[ bɛnt / ˈbɛndɪd ]" },
  { verb1: "bereave", pronunciation1: "[ bɪˈriːv ]", verb2: "bereft / bereaved", pronunciation2: "[ bɪˈrɛft / bɪˈriːvd ]", verb3: "bereft / bereaved", pronunciation3: "[ bɪˈrɛft / bɪˈriːvd ]" },
  { verb1: "bespeak", pronunciation1: "[ bɪˈspiːk ]", verb2: "bespoke", pronunciation2: "[ bɪˈspoʊk ]", verb3: "bespoke / bespoken", pronunciation3: "[ bɪˈspoʊk / bɪˈspoʊkən ]" },
  { verb1: "bet", pronunciation1: "[ bɛt ]", verb2: "bet / betted", pronunciation2: "[ bɛt / ˈbɛtɪd ]", verb3: "bet / betted", pronunciation3: "[ bɛt / ˈbɛtɪd ]" },
  { verb1: "bid", pronunciation1: "[ bɪd ]", verb2: "bad / bade / bid", pronunciation2: "[ bæd / beɪd / bɪd ]", verb3: "bid / bidden", pronunciation3: "[ bɪd / ˈbɪdn̩ ]" },
  { verb1: "bind", pronunciation1: "[ baɪnd ]", verb2: "bound", pronunciation2: "[ baʊnd ]", verb3: "bound", pronunciation3: "[ baʊnd ]" },
  { verb1: "bite", pronunciation1: "[ baɪt ]", verb2: "bit", pronunciation2: "[ bɪt ]", verb3: "bit / bitten", pronunciation3: "[ bɪt / ˈbɪtn̩ ]" },
  { verb1: "bleed", pronunciation1: "[ bliːd ]", verb2: "bled", pronunciation2: "[ blɛd ]", verb3: "bled", pronunciation3: "[ blɛd ]" },
  { verb1: "bless", pronunciation1: "[ blɛs ]", verb2: "blessed", pronunciation2: "[ blɛst ]", verb3: "blessed / blest", pronunciation3: "[ blɛst ]" },
  { verb1: "blow", pronunciation1: "[ bloʊ ]", verb2: "blew", pronunciation2: "[ bluː ]", verb3: "blown / blowed", pronunciation3: "[ bloʊn / bloʊd ]" },
  { verb1: "break", pronunciation1: "[ breɪk ]", verb2: "broke", pronunciation2: "[ broʊk ]", verb3: "broken", pronunciation3: "[ ˈbroʊkən ]" },
  { verb1: "breed", pronunciation1: "[ briːd ]", verb2: "bred", pronunciation2: "[ brɛd ]", verb3: "bred", pronunciation3: "[ brɛd ]" },
  { verb1: "bring", pronunciation1: "[ brɪŋ ]", verb2: "brought", pronunciation2: "[ brɔːt ]", verb3: "brought", pronunciation3: "[ brɔːt ]" },
  { verb1: "broadcast", pronunciation1: "[ ˈbrɔːdkæst ]", verb2: "broadcast", pronunciation2: "[ ˈbrɔːdkæst ]", verb3: "broadcast", pronunciation3: "[ ˈbrɔːdkæst ]" },
  { verb1: "build", pronunciation1: "[ bɪld ]", verb2: "built", pronunciation2: "[ bɪlt ]", verb3: "built", pronunciation3: "[ bɪlt ]" },
  { verb1: "burn", pronunciation1: "[ bɜːrn ]", verb2: "burnt / burned", pronunciation2: "[ bɜːrnt / bɜːrnd ]", verb3: "burnt / burned", pronunciation3: "[ bɜːrnt / bɜːrnd ]" },
  { verb1: "burst", pronunciation1: "[ bɜːrst ]", verb2: "burst", pronunciation2: "[ bɜːrst ]", verb3: "burst", pronunciation3: "[ bɜːrst ]" },
  { verb1: "bust", pronunciation1: "[ bʌst ]", verb2: "bust / busted", pronunciation2: "[ bʌst / ˈbʌstɪd ]", verb3: "bust / busted", pronunciation3: "[ bʌst / ˈbʌstɪd ]" },
  { verb1: "buy", pronunciation1: "[ baɪ ]", verb2: "bought", pronunciation2: "[ bɔːt ]", verb3: "bought", pronunciation3: "[ bɔːt ]" },
  // C
  // {verb1: "cast", verb2: "cast", verb3: "cast"},
  // {verb1: "catch", verb2: "caught", verb3: "caught"},
  // {verb1: "choose", verb2: "chose", verb3: "chosen"},
  // {verb1: "cling", verb2: "clung", verb3: "clung"},
  // {verb1: "come", verb2: "came", verb3: "come"},
  // {verb1: "cost", verb2: "cost", verb3: "cost"},
  // {verb1: "creep", verb2: "crept", verb3: "crept"},
  // {verb1: "crow", verb2: "crowed / crew", verb3: "crowed"},
  // {verb1: "cut", verb2: "cut", verb3: "cut"},
  { verb1: "cast", pronunciation1: "[ kæst ]", verb2: "cast", pronunciation2: "[ kæst ]", verb3: "cast", pronunciation3: "[ kæst ]" },
  { verb1: "catch", pronunciation1: "[ kætʃ ]", verb2: "caught", pronunciation2: "[ kɔːt ]", verb3: "caught", pronunciation3: "[ kɔːt ]" },
  { verb1: "choose", pronunciation1: "[ tʃuːz ]", verb2: "chose", pronunciation2: "[ tʃoʊz ]", verb3: "chosen", pronunciation3: "[ ˈtʃoʊzn ]" },
  { verb1: "cling", pronunciation1: "[ klɪŋ ]", verb2: "clung", pronunciation2: "[ klʌŋ ]", verb3: "clung", pronunciation3: "[ klʌŋ ]" },
  { verb1: "come", pronunciation1: "[ kʌm ]", verb2: "came", pronunciation2: "[ keɪm ]", verb3: "come", pronunciation3: "[ kʌm ]" },
  { verb1: "cost", pronunciation1: "[ kɔːst ]", verb2: "cost", pronunciation2: "[ kɔːst ]", verb3: "cost", pronunciation3: "[ kɔːst ]" },
  { verb1: "creep", pronunciation1: "[ kriːp ]", verb2: "crept", pronunciation2: "[ krɛpt ]", verb3: "crept", pronunciation3: "[ krɛpt ]" },
  { verb1: "crow", pronunciation1: "[ kroʊ ]", verb2: "crowed / crew", pronunciation2: "[ kroʊd / kruː ]", verb3: "crowed", pronunciation3: "[ kroʊd ]" },
  { verb1: "cut", pronunciation1: "[ kʌt ]", verb2: "cut", pronunciation2: "[ kʌt ]", verb3: "cut", pronunciation3: "[ kʌt ]" },
  // D
  // {verb1: "dare", verb2: "durst / dared", verb3: "dared"},
  // {verb1: "deal", verb2: "dealt", verb3: "dealt"},
  // {verb1: "dig", verb2: "dug", verb3: "dug"},
  // {verb1: "dive", verb2: "dived / dove", verb3: "dived"},
  // {verb1: "do", verb2: "did", verb3: "done"},
  // {verb1: "draw", verb2: "drew", verb3: "drawn"},
  // {verb1: "dream", verb2: "dreamt / dreamed", verb3: "dreamt / dreamed"},
  // {verb1: "drink", verb2: "drank", verb3: "drunk"},
  // {verb1: "drive", verb2: "drove", verb3: "driven"},
  // {verb1: "dwell", verb2: "dwelt", verb3: "dwelt"},
  { verb1: "dare", pronunciation1: "[ dɛər ]", verb2: "durst / dared", pronunciation2: "[ dɜːrst / dɛərd ]", verb3: "dared", pronunciation3: "[ dɛərd ]" },
  { verb1: "deal", pronunciation1: "[ diːl ]", verb2: "dealt", pronunciation2: "[ dɛlt ]", verb3: "dealt", pronunciation3: "[ dɛlt ]" },
  { verb1: "dig", pronunciation1: "[ dɪɡ ]", verb2: "dug", pronunciation2: "[ dʌɡ ]", verb3: "dug", pronunciation3: "[ dʌɡ ]" },
  { verb1: "dive", pronunciation1: "[ daɪv ]", verb2: "dived / dove", pronunciation2: "[ daɪvd / doʊv ]", verb3: "dived", pronunciation3: "[ daɪvd ]" },
  { verb1: "do", pronunciation1: "[ duː ]", verb2: "did", pronunciation2: "[ dɪd ]", verb3: "done", pronunciation3: "[ dʌn ]" },
  { verb1: "draw", pronunciation1: "[ drɔː ]", verb2: "drew", pronunciation2: "[ druː ]", verb3: "drawn", pronunciation3: "[ drɔːn ]" },
  { verb1: "dream", pronunciation1: "[ driːm ]", verb2: "dreamt / dreamed", pronunciation2: "[ drɛmt / driːmd ]", verb3: "dreamt / dreamed", pronunciation3: "[ drɛmt / driːmd ]" },
  { verb1: "drink", pronunciation1: "[ drɪŋk ]", verb2: "drank", pronunciation2: "[ dræŋk ]", verb3: "drunk", pronunciation3: "[ drʌŋk ]" },
  { verb1: "drive", pronunciation1: "[ draɪv ]", verb2: "drove", pronunciation2: "[ droʊv ]", verb3: "driven", pronunciation3: "[ ˈdrɪvn̩ ]" },
  { verb1: "dwell", pronunciation1: "[ dwɛl ]", verb2: "dwelt", pronunciation2: "[ dwɛlt ]", verb3: "dwelt", pronunciation3: "[ dwɛlt ]" },
  // E
  // {verb1: "eat", verb2: "ate", verb3: "eaten"},
  { verb1: "eat", pronunciation1: "[ iːt ]", verb2: "ate", pronunciation2: "[ eɪt ]", verb3: "eaten", pronunciation3: "[ ˈiːtn ]" },
  // F
  // {verb1: "fall", verb2: "fell", verb3: "fallen"},
  // {verb1: "feed", verb2: "fed", verb3: "fed"},
  // {verb1: "feel", verb2: "felt", verb3: "felt"},
  // {verb1: "fight", verb2: "fought", verb3: "fought"},
  // {verb1: "find", verb2: "found", verb3: "found"},
  // {verb1: "flee", verb2: "fled", verb3: "fled"},
  // {verb1: "fling", verb2: "flung", verb3: "flung"},
  // {verb1: "fly", verb2: "flew", verb3: "flown"},
  // {verb1: "forbid", verb2: "forbad / forbade", verb3: "forbidden"},
  // {verb1: "forecast", verb2: "forecast / forecasted", verb3: "forecast / forecasted"},
  // {verb1: "foresee", verb2: "foresaw", verb3: "foreseen"},
  // {verb1: "foretell", verb2: "foretold", verb3: "foretold"},
  // {verb1: "forget", verb2: "forgot", verb3: "forgotten"},
  // {verb1: "forgive", verb2: "forgave", verb3: "forgiven"},
  // {verb1: "forsake", verb2: "forsook", verb3: "forsaken"},
  // {verb1: "freeze", verb2: "froze", verb3: "frozen"},
  { verb1: "fall", pronunciation1: "[ fɔːl ]", verb2: "fell", pronunciation2: "[ fɛl ]", verb3: "fallen", pronunciation3: "[ ˈfɔːlən ]" },
  { verb1: "feed", pronunciation1: "[ fiːd ]", verb2: "fed", pronunciation2: "[ fɛd ]", verb3: "fed", pronunciation3: "[ fɛd ]" },
  { verb1: "feel", pronunciation1: "[ fiːl ]", verb2: "felt", pronunciation2: "[ fɛlt ]", verb3: "felt", pronunciation3: "[ fɛlt ]" },
  { verb1: "fight", pronunciation1: "[ faɪt ]", verb2: "fought", pronunciation2: "[ fɔːt ]", verb3: "fought", pronunciation3: "[ fɔːt ]" },
  { verb1: "find", pronunciation1: "[ faɪnd ]", verb2: "found", pronunciation2: "[ faʊnd ]", verb3: "found", pronunciation3: "[ faʊnd ]" },
  { verb1: "flee", pronunciation1: "[ fliː ]", verb2: "fled", pronunciation2: "[ flɛd ]", verb3: "fled", pronunciation3: "[ flɛd ]" },
  { verb1: "fling", pronunciation1: "[ flɪŋ ]", verb2: "flung", pronunciation2: "[ flʌŋ ]", verb3: "flung", pronunciation3: "[ flʌŋ ]" },
  { verb1: "fly", pronunciation1: "[ flaɪ ]", verb2: "flew", pronunciation2: "[ fluː ]", verb3: "flown", pronunciation3: "[ floʊn ]" },
  { verb1: "forbid", pronunciation1: "[ fərˈbɪd ]", verb2: "forbad / forbade", pronunciation2: "[ fɔːrˈbæd / fɔːrˈbeɪd ]", verb3: "forbidden", pronunciation3: "[ fɔːrˈbɪdn̩ ]" },
  { verb1: "forecast", pronunciation1: "[ ˈfɔːrkæst ]", verb2: "forecast / forecasted", pronunciation2: "[ ˈfɔːrkæst / ˈfɔːrkæstɪd ]", verb3: "forecast / forecasted", pronunciation3: "[ ˈfɔːrkæst / ˈfɔːrkæstɪd ]" },
  { verb1: "foresee", pronunciation1: "[ fɔːrˈsiː ]", verb2: "foresaw", pronunciation2: "[ fɔːrˈsɔː ]", verb3: "foreseen", pronunciation3: "[ fɔːrˈsiːn ]" },
  { verb1: "foretell", pronunciation1: "[ fɔːrˈtɛl ]", verb2: "foretold", pronunciation2: "[ fɔːrˈtoʊld ]", verb3: "foretold", pronunciation3: "[ fɔːrˈtoʊld ]" },
  { verb1: "forget", pronunciation1: "[ fərˈɡɛt ]", verb2: "forgot", pronunciation2: "[ fərˈɡɒt ]", verb3: "forgotten", pronunciation3: "[ fərˈɡɒtn̩ ]" },
  { verb1: "forgive", pronunciation1: "[ fərˈɡɪv ]", verb2: "forgave", pronunciation2: "[ fərˈɡeɪv ]", verb3: "forgiven", pronunciation3: "[ fərˈɡɪvn̩ ]" },
  { verb1: "forsake", pronunciation1: "[ fɔːrˈseɪk ]", verb2: "forsook", pronunciation2: "[ fɔːrˈsʊk ]", verb3: "forsaken", pronunciation3: "[ fɔːrˈseɪkən ]" },
  { verb1: "freeze", pronunciation1: "[ friːz ]", verb2: "froze", pronunciation2: "[ froʊz ]", verb3: "frozen", pronunciation3: "[ ˈfroʊzn̩ ]" },
  // G
  // {verb1: "get", verb2: "got", verb3: "got"},
  // {verb1: "gild", verb2: "gilt / gilded", verb3: "gild / gilded"},
  // {verb1: "give", verb2: "gave", verb3: "given"},
  // {verb1: "go", verb2: "went", verb3: "gone"},
  // {verb1: "grave", verb2: "graved", verb3: "graved / graven"},
  // {verb1: "grind", verb2: "ground", verb3: "ground"},
  // {verb1: "grow", verb2: "grew", verb3: "grown"},
  { verb1: "get", pronunciation1: "[ ɡɛt ]", verb2: "got", pronunciation2: "[ ɡɒt ]", verb3: "got", pronunciation3: "[ ɡɒt ]" },
  { verb1: "gild", pronunciation1: "[ ɡɪld ]", verb2: "gilt / gilded", pronunciation2: "[ ɡɪlt / ˈɡɪldɪd ]", verb3: "gilded / gilt", pronunciation3: "[ ˈɡɪldɪd / ɡɪlt ]" },
  { verb1: "give", pronunciation1: "[ ɡɪv ]", verb2: "gave", pronunciation2: "[ ɡeɪv ]", verb3: "given", pronunciation3: "[ ˈɡɪvn̩ ]" },
  { verb1: "go", pronunciation1: "[ ɡoʊ ]", verb2: "went", pronunciation2: "[ wɛnt ]", verb3: "gone", pronunciation3: "[ ɡɒn ]" },
  { verb1: "grave", pronunciation1: "[ ɡreɪv ]", verb2: "graved", pronunciation2: "[ ɡreɪvd ]", verb3: "graved / graven", pronunciation3: "[ ɡreɪvd / ˈɡreɪvən ]" },
  { verb1: "grind", pronunciation1: "[ ɡraɪnd ]", verb2: "ground", pronunciation2: "[ ɡraʊnd ]", verb3: "ground", pronunciation3: "[ ɡraʊnd ]" },
  { verb1: "grow", pronunciation1: "[ ɡroʊ ]", verb2: "grew", pronunciation2: "[ ɡruː ]", verb3: "grown", pronunciation3: "[ ɡroʊn ]" },
  // H
  // {verb1: "hang", verb2: "hung / hanged", verb3: "hung / hanged",},
  // {verb1: "have", verb2: "had", verb3: "had"},
  // {verb1: "hear", verb2: "heard", verb3: "heard"},
  // {verb1: "heave", verb2: "heaved / hove", verb3: "heaved / hove",},
  // {verb1: "hide", verb2: "hid", verb3: "hidden"},
  // {verb1: "hit", verb2: "hit", verb3: "hit"},
  // {verb1: "hold", verb2: "held", verb3: "held"},
  // {verb1: "hurt", verb2: "hurt", verb3: "hurt"},
  { verb1: "hang", pronunciation1: "[ hæŋ ]", verb2: "hung / hanged", pronunciation2: "[ hʌŋ / hæŋd ]", verb3: "hung / hanged", pronunciation3: "[ hʌŋ / hæŋd ]" },
  { verb1: "have", pronunciation1: "[ hæv ]", verb2: "had", pronunciation2: "[ hæd ]", verb3: "had", pronunciation3: "[ hæd ]" },
  { verb1: "hear", pronunciation1: "[ hɪər ]", verb2: "heard", pronunciation2: "[ hɜːrd ]", verb3: "heard", pronunciation3: "[ hɜːrd ]" },
  { verb1: "heave", pronunciation1: "[ hiːv ]", verb2: "heaved / hove", pronunciation2: "[ hiːvd / hoʊv ]", verb3: "heaved / hove", pronunciation3: "[ hiːvd / hoʊv ]" },
  { verb1: "hide", pronunciation1: "[ haɪd ]", verb2: "hid", pronunciation2: "[ hɪd ]", verb3: "hidden", pronunciation3: "[ ˈhɪdn̩ ]" },
  { verb1: "hit", pronunciation1: "[ hɪt ]", verb2: "hit", pronunciation2: "[ hɪt ]", verb3: "hit", pronunciation3: "[ hɪt ]" },
  { verb1: "hold", pronunciation1: "[ hoʊld ]", verb2: "held", pronunciation2: "[ hɛld ]", verb3: "held", pronunciation3: "[ hɛld ]" },
  { verb1: "hurt", pronunciation1: "[ hɜːrt ]", verb2: "hurt", pronunciation2: "[ hɜːrt ]", verb3: "hurt", pronunciation3: "[ hɜːrt ]" },
  // I
  // {verb1: "input", verb2: "input / inputted", verb3: "input / inputted",},
  { verb1: "input", pronunciation1: "[ ˈɪnpʊt ]", verb2: "input / inputted", pronunciation2: "[ ˈɪnpʊt / ˈɪnpʊtɪd ]", verb3: "input / inputted", pronunciation3: "[ ˈɪnpʊt / ˈɪnpʊtɪd ]" },
  // K
  // {verb1: "keep", verb2: "kept", verb3: "kept"},
  // {verb1: "kneel", verb2: "knelt / kneeled", verb3: "knelt / kneeled"},
  // {verb1: "knit", verb2: "knit / knitted", verb3: "knit / knitted"},
  // {verb1: "know", verb2: "knew", verb3: "known"},
  { verb1: "keep", pronunciation1: "[ kiːp ]", verb2: "kept", pronunciation2: "[ kɛpt ]", verb3: "kept", pronunciation3: "[ kɛpt ]" },
  { verb1: "kneel", pronunciation1: "[ niːl ]", verb2: "knelt / kneeled", pronunciation2: "[ nɛlt / niːld ]", verb3: "knelt / kneeled", pronunciation3: "[ nɛlt / niːld ]" },
  { verb1: "knit", pronunciation1: "[ nɪt ]", verb2: "knit / knitted", pronunciation2: "[ nɪt / ˈnɪtɪd ]", verb3: "knit / knitted", pronunciation3: "[ nɪt / ˈnɪtɪd ]" },
  { verb1: "know", pronunciation1: "[ noʊ ]", verb2: "knew", pronunciation2: "[ nuː ]", verb3: "known", pronunciation3: "[ noʊn ]" },
  // L
  // {verb1: "lay", verb2: "laid", verb3: "laid"},
  // {verb1: "lead", verb2: "led", verb3: "led"},
  // {verb1: "lean", verb2: "leant / leaned", verb3: "leant / leaned"},
  // {verb1: "leap", verb2: "leapt / leaped", verb3: "leapt / leaped"},
  // {verb1: "learn", verb2: "learnt / learned", verb3: "learnt / learned"},
  // {verb1: "leave", verb2: "left", verb3: "left"},
  // {verb1: "lend", verb2: "lent", verb3: "lent"},
  // {verb1: "let", verb2: "let", verb3: "let"},
  // {verb1: "lie", verb2: "lay", verb3: "lain"},
  // {verb1: "light", verb2: "lit / lighted", verb3: "lit / lighted"},
  // {verb1: "lose", verb2: "lost", verb3: "lost"},
  { verb1: "lay", pronunciation1: "[ leɪ ]", verb2: "laid", pronunciation2: "[ leɪd ]", verb3: "laid", pronunciation3: "[ leɪd ]" },
  { verb1: "lead", pronunciation1: "[ liːd ]", verb2: "led", pronunciation2: "[ lɛd ]", verb3: "led", pronunciation3: "[ lɛd ]" },
  { verb1: "lean", pronunciation1: "[ liːn ]", verb2: "leant / leaned", pronunciation2: "[ lɛnt / liːnd ]", verb3: "leant / leaned", pronunciation3: "[ lɛnt / liːnd ]" },
  { verb1: "leap", pronunciation1: "[ liːp ]", verb2: "leapt / leaped", pronunciation2: "[ lɛpt / liːpt ]", verb3: "leapt / leaped", pronunciation3: "[ lɛpt / liːpt ]" },
  { verb1: "learn", pronunciation1: "[ lɜːrn ]", verb2: "learnt / learned", pronunciation2: "[ lɜːrnt / lɜːrnd ]", verb3: "learnt / learned", pronunciation3: "[ lɜːrnt / lɜːrnd ]" },
  { verb1: "leave", pronunciation1: "[ liːv ]", verb2: "left", pronunciation2: "[ lɛft ]", verb3: "left", pronunciation3: "[ lɛft ]" },
  { verb1: "lend", pronunciation1: "[ lɛnd ]", verb2: "lent", pronunciation2: "[ lɛnt ]", verb3: "lent", pronunciation3: "[ lɛnt ]" },
  { verb1: "let", pronunciation1: "[ lɛt ]", verb2: "let", pronunciation2: "[ lɛt ]", verb3: "let", pronunciation3: "[ lɛt ]" },
  { verb1: "lie", pronunciation1: "[ laɪ ]", verb2: "lay", pronunciation2: "[ leɪ ]", verb3: "lain", pronunciation3: "[ leɪn ]" },
  { verb1: "light", pronunciation1: "[ laɪt ]", verb2: "lit / lighted", pronunciation2: "[ lɪt / ˈlaɪtɪd ]", verb3: "lit / lighted", pronunciation3: "[ lɪt / ˈlaɪtɪd ]" },
  { verb1: "lose", pronunciation1: "[ luːz ]", verb2: "lost", pronunciation2: "[ lɔːst ]", verb3: "lost", pronunciation3: "[ lɔːst ]" },
  // M
  // {verb1: "make", verb2: "made", verb3: "made"},
  // {verb1: "mean", verb2: "meant", verb3: "meant"},
  // {verb1: "meet", verb2: "met", verb3: "met"},
  // {verb1: "mislead", verb2: "misled", verb3: "misled"},
  // {verb1: "misspell", verb2: "misspelt / misspelled", verb3: "misspelt / misspelled"},
  // {verb1: "misunderstand", verb2: "misunderstood", verb3: "misunderstood"},
  // {verb1: "mow", verb2: "mowed", verb3: "mown / mowed",},
  { verb1: "make", pronunciation1: "[ meɪk ]", verb2: "made", pronunciation2: "[ meɪd ]", verb3: "made", pronunciation3: "[ meɪd ]" },
  { verb1: "mean", pronunciation1: "[ miːn ]", verb2: "meant", pronunciation2: "[ mɛnt ]", verb3: "meant", pronunciation3: "[ mɛnt ]" },
  { verb1: "meet", pronunciation1: "[ miːt ]", verb2: "met", pronunciation2: "[ mɛt ]", verb3: "met", pronunciation3: "[ mɛt ]" },
  { verb1: "mislead", pronunciation1: "[ ˌmɪsˈliːd ]", verb2: "misled", pronunciation2: "[ ˌmɪsˈlɛd ]", verb3: "misled", pronunciation3: "[ ˌmɪsˈlɛd ]" },
  { verb1: "misspell", pronunciation1: "[ ˌmɪsˈspɛl ]", verb2: "misspelt / misspelled", pronunciation2: "[ ˌmɪsˈspɛlt / ˌmɪsˈspɛld ]", verb3: "misspelt / misspelled", pronunciation3: "[ ˌmɪsˈspɛlt / ˌmɪsˈspɛld ]" },
  { verb1: "misunderstand", pronunciation1: "[ ˌmɪsʌndərˈstænd ]", verb2: "misunderstood", pronunciation2: "[ ˌmɪsʌndərˈstʊd ]", verb3: "misunderstood", pronunciation3: "[ ˌmɪsʌndərˈstʊd ]" },
  { verb1: "mow", pronunciation1: "[ moʊ ]", verb2: "mowed", pronunciation2: "[ moʊd ]", verb3: "mown / mowed", pronunciation3: "[ moʊn / moʊd ]" },
  // O
  // {verb1: "outbid", verb2: "outbid", verb3: "outbid"},
  // {verb1: "outdo", verb2: "outdid", verb3: "outdone"},
  // {verb1: "outrun", verb2: "outran", verb3: "outrun"},
  // {verb1: "outsell", verb2: "outsold", verb3: "outsold"},
  // {verb1: "overcome", verb2: "overcame", verb3: "overcome"},
  // {verb1: "overeat", verb2: "overate", verb3: "overeaten"},
  // {verb1: "overhang", verb2: "overhung", verb3: "overhung"},
  // {verb1: "overhear", verb2: "overheard", verb3: "overheard"},
  // {verb1: "overpay", verb2: "overpaid", verb3: "overpaid"},
  // {verb1: "override", verb2: "overrode", verb3: "overridden"},
  // {verb1: "overrun", verb2: "overran", verb3: "overrun"},
  // {verb1: "oversee", verb2: "oversaw", verb3: "overseen"},
  // {verb1: "oversleep", verb2: "overslept", verb3: "overslept"},
  // {verb1: "overtake", verb2: "overtook", verb3: "overtaken"},
  // {verb1: "overthrow", verb2: "overthrew", verb3: "overthrown"},
  { verb1: "outbid", pronunciation1: "[ ˌaʊtˈbɪd ]", verb2: "outbid", pronunciation2: "[ ˌaʊtˈbɪd ]", verb3: "outbid", pronunciation3: "[ ˌaʊtˈbɪd ]" },
  { verb1: "outdo", pronunciation1: "[ ˌaʊtˈduː ]", verb2: "outdid", pronunciation2: "[ ˌaʊtˈdɪd ]", verb3: "outdone", pronunciation3: "[ ˌaʊtˈdʌn ]" },
  { verb1: "outrun", pronunciation1: "[ ˌaʊtˈrʌn ]", verb2: "outran", pronunciation2: "[ ˌaʊtˈræn ]", verb3: "outrun", pronunciation3: "[ ˌaʊtˈrʌn ]" },
  { verb1: "outsell", pronunciation1: "[ ˌaʊtˈsɛl ]", verb2: "outsold", pronunciation2: "[ ˌaʊtˈsoʊld ]", verb3: "outsold", pronunciation3: "[ ˌaʊtˈsoʊld ]" },
  { verb1: "overcome", pronunciation1: "[ ˌoʊvərˈkʌm ]", verb2: "overcame", pronunciation2: "[ ˌoʊvərˈkeɪm ]", verb3: "overcome", pronunciation3: "[ ˌoʊvərˈkʌm ]" },
  { verb1: "overeat", pronunciation1: "[ ˌoʊvərˈiːt ]", verb2: "overate", pronunciation2: "[ ˌoʊvərˈeɪt ]", verb3: "overeaten", pronunciation3: "[ ˌoʊvərˈiːtn̩ ]" },
  { verb1: "overhang", pronunciation1: "[ ˌoʊvərˈhæŋ ]", verb2: "overhung", pronunciation2: "[ ˌoʊvərˈhʌŋ ]", verb3: "overhung", pronunciation3: "[ ˌoʊvərˈhʌŋ ]" },
  { verb1: "overhear", pronunciation1: "[ ˌoʊvərˈhɪr ]", verb2: "overheard", pronunciation2: "[ ˌoʊvərˈhɜːrd ]", verb3: "overheard", pronunciation3: "[ ˌoʊvərˈhɜːrd ]" },
  { verb1: "overpay", pronunciation1: "[ ˌoʊvərˈpeɪ ]", verb2: "overpaid", pronunciation2: "[ ˌoʊvərˈpeɪd ]", verb3: "overpaid", pronunciation3: "[ ˌoʊvərˈpeɪd ]" },
  { verb1: "override", pronunciation1: "[ ˌoʊvərˈraɪd ]", verb2: "overrode", pronunciation2: "[ ˌoʊvərˈroʊd ]", verb3: "overridden", pronunciation3: "[ ˌoʊvərˈrɪdn̩ ]" },
  { verb1: "overrun", pronunciation1: "[ ˌoʊvərˈrʌn ]", verb2: "overran", pronunciation2: "[ ˌoʊvərˈræn ]", verb3: "overrun", pronunciation3: "[ ˌoʊvərˈrʌn ]" },
  { verb1: "oversee", pronunciation1: "[ ˌoʊvərˈsiː ]", verb2: "oversaw", pronunciation2: "[ ˌoʊvərˈsɔː ]", verb3: "overseen", pronunciation3: "[ ˌoʊvərˈsiːn ]" },
  { verb1: "oversleep", pronunciation1: "[ ˌoʊvərˈsliːp ]", verb2: "overslept", pronunciation2: "[ ˌoʊvərˈslɛpt ]", verb3: "overslept", pronunciation3: "[ ˌoʊvərˈslɛpt ]" },
  { verb1: "overtake", pronunciation1: "[ ˌoʊvərˈteɪk ]", verb2: "overtook", pronunciation2: "[ ˌoʊvərˈtʊk ]", verb3: "overtaken", pronunciation3: "[ ˌoʊvərˈteɪkən ]" },
  { verb1: "overthrow", pronunciation1: "[ ˌoʊvərˈθroʊ ]", verb2: "overthrew", pronunciation2: "[ ˌoʊvərˈθruː ]", verb3: "overthrown", pronunciation3: "[ ˌoʊvərˈθroʊn ]" },
  // P
  // {verb1: "pay", verb2: "paid", verb3: "paid"},
  // {verb1: "plead", verb2: "pleaded / pled", verb3: "pleaded / pled"},
  // {verb1: "prove", verb2: "proved", verb3: "proved / proven",},
  // {verb1: "put", verb2: "put", verb3: "put"},
  { verb1: "pay", pronunciation1: "[ peɪ ]", verb2: "paid", pronunciation2: "[ peɪd ]", verb3: "paid", pronunciation3: "[ peɪd ]" },
  { verb1: "plead", pronunciation1: "[ pliːd ]", verb2: "pleaded / pled", pronunciation2: "[ ˈpliːdɪd / plɛd ]", verb3: "pleaded / pled", pronunciation3: "[ ˈpliːdɪd / plɛd ]" },
  { verb1: "prove", pronunciation1: "[ pruːv ]", verb2: "proved", pronunciation2: "[ pruːvd ]", verb3: "proved / proven", pronunciation3: "[ pruːvd / ˈpruːvən ]" },
  { verb1: "put", pronunciation1: "[ pʊt ]", verb2: "put", pronunciation2: "[ pʊt ]", verb3: "put", pronunciation3: "[ pʊt ]" },
  // Q
  // {verb1: "quit", verb2: "quit / quitted", verb3: "quit / quitted"},
  { verb1: "quit", pronunciation1: "[ kwɪt ]", verb2: "quit / quitted", pronunciation2: "[ kwɪt / ˈkwɪtɪd ]", verb3: "quit / quitted", pronunciation3: "[ kwɪt / ˈkwɪtɪd ]" },
  // R
  // {verb1: "read", verb2: "read / red", verb3: "read / red"},
  // {verb1: "rebuild", verb2: "rebuilt", verb3: "rebuilt"},
  // {verb1: "redo", verb2: "redid", verb3: "redone"},
  // {verb1: "rend", verb2: "rent", verb3: "rent"},
  // {verb1: "repay", verb2: "repaid", verb3: "repaid"},
  // {verb1: "reset", verb2: "reset", verb3: "reset"},
  // {verb1: "resit", verb2: "resat", verb3: "resat"},
  // {verb1: "retell", verb2: "retold", verb3: "retold"},
  // {verb1: "rid", verb2: "rid / ridded", verb3: "rid / ridded"},
  // {verb1: "ride", verb2: "rode", verb3: "ridden"},
  // {verb1: "ring", verb2: "rang", verb3: "rung"},
  // {verb1: "rise", verb2: "rose", verb3: "risen"},
  // {verb1: "run", verb2: "ran", verb3: "run"},
  { verb1: "read", pronunciation1: "[ riːd ]", verb2: "read / red", pronunciation2: "[ rɛd ]", verb3: "read / red", pronunciation3: "[ rɛd ]" },
  { verb1: "rebuild", pronunciation1: "[ ˌriːˈbɪld ]", verb2: "rebuilt", pronunciation2: "[ ˌriːˈbɪlt ]", verb3: "rebuilt", pronunciation3: "[ ˌriːˈbɪlt ]" },
  { verb1: "redo", pronunciation1: "[ ˌriːˈduː ]", verb2: "redid", pronunciation2: "[ ˌriːˈdɪd ]", verb3: "redone", pronunciation3: "[ ˌriːˈdʌn ]" },
  { verb1: "rend", pronunciation1: "[ rɛnd ]", verb2: "rent", pronunciation2: "[ rɛnt ]", verb3: "rent", pronunciation3: "[ rɛnt ]" },
  { verb1: "repay", pronunciation1: "[ ˌriːˈpeɪ ]", verb2: "repaid", pronunciation2: "[ ˌriːˈpeɪd ]", verb3: "repaid", pronunciation3: "[ ˌriːˈpeɪd ]" },
  { verb1: "reset", pronunciation1: "[ ˌriːˈsɛt ]", verb2: "reset", pronunciation2: "[ ˌriːˈsɛt ]", verb3: "reset", pronunciation3: "[ ˌriːˈsɛt ]" },
  { verb1: "resit", pronunciation1: "[ ˌriːˈsɪt ]", verb2: "resat", pronunciation2: "[ ˌriːˈsæt ]", verb3: "resat", pronunciation3: "[ ˌriːˈsæt ]" },
  { verb1: "retell", pronunciation1: "[ ˌriːˈtɛl ]", verb2: "retold", pronunciation2: "[ ˌriːˈtoʊld ]", verb3: "retold", pronunciation3: "[ ˌriːˈtoʊld ]" },
  { verb1: "rid", pronunciation1: "[ rɪd ]", verb2: "rid / ridded", pronunciation2: "[ rɪd / ˈrɪdɪd ]", verb3: "rid / ridded", pronunciation3: "[ rɪd / ˈrɪdɪd ]" },
  { verb1: "ride", pronunciation1: "[ raɪd ]", verb2: "rode", pronunciation2: "[ roʊd ]", verb3: "ridden", pronunciation3: "[ ˈrɪdn̩ ]" },
  { verb1: "ring", pronunciation1: "[ rɪŋ ]", verb2: "rang", pronunciation2: "[ ræŋ ]", verb3: "rung", pronunciation3: "[ rʌŋ ]" },
  { verb1: "rise", pronunciation1: "[ raɪz ]", verb2: "rose", pronunciation2: "[ roʊz ]", verb3: "risen", pronunciation3: "[ ˈrɪzn̩ ]" },
  { verb1: "run", pronunciation1: "[ rʌn ]", verb2: "ran", pronunciation2: "[ ræn ]", verb3: "run", pronunciation3: "[ rʌn ]" },
  // S
  // {verb1: "saw", verb2: "sawed", verb3: "sawn / sawed",},
  // {verb1: "say", verb2: "said", verb3: "said"},
  // {verb1: "see", verb2: "saw", verb3: "seen"},
  // {verb1: "seek", verb2: "sought", verb3: "sought"},
  // {verb1: "sell", verb2: "sold", verb3: "sold"},
  // {verb1: "send", verb2: "sent", verb3: "sent"},
  // {verb1: "set", verb2: "set", verb3: "set"},
  // {verb1: "sew", verb2: "sewed", verb3: "sewed / sewn"},
  // {verb1: "shake", verb2: "shook", verb3: "shaken"},
  // {verb1: "shave", verb2: "shaved", verb3: "shaved / shaven"},
  // {verb1: "shed", verb2: "shed", verb3: "shed"},
  // {verb1: "shine", verb2: "shone / shined", verb3: "shone / shined"},
  // {verb1: "shoot", verb2: "shot", verb3: "shot"},
  // {verb1: "show", verb2: "showed", verb3: "shown / showed"},
  // {verb1: "shred", verb2: "shred / shredded", verb3: "shred / shredded"},
  // {verb1: "shrink", verb2: "shrank / shrunk", verb3: "shrunk"},
  // {verb1: "shut", verb2: "shut", verb3: "shut"},
  // {verb1: "sing", verb2: "sang", verb3: "sung"},
  // {verb1: "sink", verb2: "sank", verb3: "sunk"},
  // {verb1: "sit", verb2: "sat", verb3: "sat"},
  // {verb1: "sleep", verb2: "slept", verb3: "slept"},
  // {verb1: "slide", verb2: "slid", verb3: "slid"},
  // {verb1: "sling", verb2: "slung", verb3: "slung"},
  // {verb1: "slit", verb2: "slit", verb3: "slit"},
  // {verb1: "smell", verb2: "smelt / smelled", verb3: "smelt / smelled"},
  // {verb1: "sow", verb2: "sowed", verb3: "sowed / sown"},
  // {verb1: "speak", verb2: "spoke", verb3: "spoken"},
  // {verb1: "speed", verb2: "sped / speeded", verb3: "sped / speeded"},
  // {verb1: "spend", verb2: "spent", verb3: "spent"},
  // {verb1: "spell", verb2: "spelt / spelled", verb3: "spell / spelled"},
  // {verb1: "spill", verb2: "spilt / spilled", verb3: "spilt / spilled",},
  // {verb1: "spin", verb2: "spun / span", verb3: "spun"},
  // {verb1: "spit", verb2: "spat / spit", verb3: "spat / spit"},
  // {verb1: "split", verb2: "split", verb3: "split"},
  // {verb1: "spoil", verb2: "spoilt / spoiled", verb3: "spoilt / spoiled",},
  // {verb1: "spread", verb2: "spread", verb3: "spread"},
  // {verb1: "spring", verb2: "sprang", verb3: "sprung"},
  // {verb1: "stand", verb2: "stood", verb3: "stood"},
  // {verb1: "steal", verb2: "stole", verb3: "stolen"},
  // {verb1: "stick", verb2: "stuck", verb3: "stuck"},
  // {verb1: "sting", verb2: "stung", verb3: "stung"},
  // {verb1: "stink", verb2: "stank / stunk", verb3: "stunk"},
  // {verb1: "strew", verb2: "strewed", verb3: "strewn / strewed"},
  // {verb1: "stride", verb2: "strode", verb3: "stridden"},
  // {verb1: "strike", verb2: "struck", verb3: "struck"},
  // {verb1: "string", verb2: "strung", verb3: "strung"},
  // {verb1: "strive", verb2: "strove", verb3: "striven"},
  // {verb1: "swear", verb2: "swore", verb3: "sworn"},
  // {verb1: "sweep", verb2: "swept", verb3: "swept"},
  // {verb1: "swell", verb2: "swelled", verb3: "swollen / swelled",},
  // {verb1: "swim", verb2: "swam", verb3: "swum"},
  // {verb1: "swing", verb2: "swung", verb3: "swung"},
  { verb1: "saw", pronunciation1: "[ sɔː ]", verb2: "sawed", pronunciation2: "[ sɔːd ]", verb3: "sawn / sawed", pronunciation3: "[ sɔːn / sɔːd ]" },
  { verb1: "say", pronunciation1: "[ seɪ ]", verb2: "said", pronunciation2: "[ sɛd ]", verb3: "said", pronunciation3: "[ sɛd ]" },
  { verb1: "see", pronunciation1: "[ siː ]", verb2: "saw", pronunciation2: "[ sɔː ]", verb3: "seen", pronunciation3: "[ siːn ]" },
  { verb1: "seek", pronunciation1: "[ siːk ]", verb2: "sought", pronunciation2: "[ sɔːt ]", verb3: "sought", pronunciation3: "[ sɔːt ]" },
  { verb1: "sell", pronunciation1: "[ sɛl ]", verb2: "sold", pronunciation2: "[ soʊld ]", verb3: "sold", pronunciation3: "[ soʊld ]" },
  { verb1: "send", pronunciation1: "[ sɛnd ]", verb2: "sent", pronunciation2: "[ sɛnt ]", verb3: "sent", pronunciation3: "[ sɛnt ]" },
  { verb1: "set", pronunciation1: "[ sɛt ]", verb2: "set", pronunciation2: "[ sɛt ]", verb3: "set", pronunciation3: "[ sɛt ]" },
  { verb1: "sew", pronunciation1: "[ soʊ ]", verb2: "sewed", pronunciation2: "[ soʊd ]", verb3: "sewed / sewn", pronunciation3: "[ soʊd / soʊn ]" },
  { verb1: "shake", pronunciation1: "[ ʃeɪk ]", verb2: "shook", pronunciation2: "[ ʃʊk ]", verb3: "shaken", pronunciation3: "[ ˈʃeɪkən ]" },
  { verb1: "shave", pronunciation1: "[ ʃeɪv ]", verb2: "shaved", pronunciation2: "[ ʃeɪvd ]", verb3: "shaved / shaven", pronunciation3: "[ ʃeɪvd / ˈʃeɪvən ]" },
  { verb1: "shed", pronunciation1: "[ ʃɛd ]", verb2: "shed", pronunciation2: "[ ʃɛd ]", verb3: "shed", pronunciation3: "[ ʃɛd ]" },
  { verb1: "shine", pronunciation1: "[ ʃaɪn ]", verb2: "shone / shined", pronunciation2: "[ ʃoʊn / ʃaɪnd ]", verb3: "shone / shined", pronunciation3: "[ ʃoʊn / ʃaɪnd ]" },
  { verb1: "shoot", pronunciation1: "[ ʃuːt ]", verb2: "shot", pronunciation2: "[ ʃɒt ]", verb3: "shot", pronunciation3: "[ ʃɒt ]" },
  { verb1: "show", pronunciation1: "[ ʃoʊ ]", verb2: "showed", pronunciation2: "[ ʃoʊd ]", verb3: "shown / showed", pronunciation3: "[ ʃoʊn / ʃoʊd ]" },
  { verb1: "shred", pronunciation1: "[ ʃrɛd ]", verb2: "shred / shredded", pronunciation2: "[ ʃrɛd / ˈʃrɛdɪd ]", verb3: "shred / shredded", pronunciation3: "[ ʃrɛd / ˈʃrɛdɪd ]" },
  { verb1: "shrink", pronunciation1: "[ ʃrɪŋk ]", verb2: "shrank / shrunk", pronunciation2: "[ ʃræŋk / ʃrʌŋk ]", verb3: "shrunk", pronunciation3: "[ ʃrʌŋk ]" },
  { verb1: "shut", pronunciation1: "[ ʃʌt ]", verb2: "shut", pronunciation2: "[ ʃʌt ]", verb3: "shut", pronunciation3: "[ ʃʌt ]" },
  { verb1: "sing", pronunciation1: "[ sɪŋ ]", verb2: "sang", pronunciation2: "[ sæŋ ]", verb3: "sung", pronunciation3: "[ sʌŋ ]" },
  { verb1: "sink", pronunciation1: "[ sɪŋk ]", verb2: "sank", pronunciation2: "[ sæŋk ]", verb3: "sunk", pronunciation3: "[ sʌŋk ]" },
  { verb1: "sit", pronunciation1: "[ sɪt ]", verb2: "sat", pronunciation2: "[ sæt ]", verb3: "sat", pronunciation3: "[ sæt ]" },
  { verb1: "sleep", pronunciation1: "[ sliːp ]", verb2: "slept", pronunciation2: "[ slɛpt ]", verb3: "slept", pronunciation3: "[ slɛpt ]" },
  { verb1: "slide", pronunciation1: "[ slaɪd ]", verb2: "slid", pronunciation2: "[ slɪd ]", verb3: "slid", pronunciation3: "[ slɪd ]" },
  { verb1: "sling", pronunciation1: "[ slɪŋ ]", verb2: "slung", pronunciation2: "[ slʌŋ ]", verb3: "slung", pronunciation3: "[ slʌŋ ]" },
  { verb1: "slit", pronunciation1: "[ slɪt ]", verb2: "slit", pronunciation2: "[ slɪt ]", verb3: "slit", pronunciation3: "[ slɪt ]" },
  { verb1: "smell", pronunciation1: "[ smɛl ]", verb2: "smelt / smelled", pronunciation2: "[ smɛlt / smɛld ]", verb3: "smelt / smelled", pronunciation3: "[ smɛlt / smɛld ]" },
  { verb1: "sow", pronunciation1: "[ soʊ ]", verb2: "sowed", pronunciation2: "[ soʊd ]", verb3: "sowed / sown", pronunciation3: "[ soʊd / soʊn ]" },
  { verb1: "speak", pronunciation1: "[ spiːk ]", verb2: "spoke", pronunciation2: "[ spoʊk ]", verb3: "spoken", pronunciation3: "[ ˈspoʊkən ]" },
  { verb1: "speed", pronunciation1: "[ spiːd ]", verb2: "sped / speeded", pronunciation2: "[ spɛd / ˈspiːdɪd ]", verb3: "sped / speeded", pronunciation3: "[ spɛd / ˈspiːdɪd ]" },
  { verb1: "spend", pronunciation1: "[ spɛnd ]", verb2: "spent", pronunciation2: "[ spɛnt ]", verb3: "spent", pronunciation3: "[ spɛnt ]" },
  { verb1: "spell", pronunciation1: "[ spɛl ]", verb2: "spelt / spelled", pronunciation2: "[ spɛlt / spɛld ]", verb3: "spelt / spelled", pronunciation3: "[ spɛlt / spɛld ]" },
  { verb1: "spill", pronunciation1: "[ spɪl ]", verb2: "spilt / spilled", pronunciation2: "[ spɪlt / spɪld ]", verb3: "spilt / spilled", pronunciation3: "[ spɪlt / spɪld ]" },
  { verb1: "spin", pronunciation1: "[ spɪn ]", verb2: "spun / span", pronunciation2: "[ spʌn / spæn ]", verb3: "spun", pronunciation3: "[ spʌn ]" },
  { verb1: "spit", pronunciation1: "[ spɪt ]", verb2: "spat / spit", pronunciation2: "[ spæt / spɪt ]", verb3: "spat / spit", pronunciation3: "[ spæt / spɪt ]" },
  { verb1: "split", pronunciation1: "[ splɪt ]", verb2: "split", pronunciation2: "[ splɪt ]", verb3: "split", pronunciation3: "[ splɪt ]" },
  { verb1: "spoil", pronunciation1: "[ spɔɪl ]", verb2: "spoilt / spoiled", pronunciation2: "[ spɔɪlt / spɔɪld ]", verb3: "spoilt / spoiled", pronunciation3: "[ spɔɪlt / spɔɪld ]" },
  { verb1: "spread", pronunciation1: "[ sprɛd ]", verb2: "spread", pronunciation2: "[ sprɛd ]", verb3: "spread", pronunciation3: "[ sprɛd ]" },
  { verb1: "spring", pronunciation1: "[ sprɪŋ ]", verb2: "sprang", pronunciation2: "[ spræŋ ]", verb3: "sprung", pronunciation3: "[ sprʌŋ ]" },
  { verb1: "stand", pronunciation1: "[ stænd ]", verb2: "stood", pronunciation2: "[ stʊd ]", verb3: "stood", pronunciation3: "[ stʊd ]" },
  { verb1: "steal", pronunciation1: "[ stiːl ]", verb2: "stole", pronunciation2: "[ stoʊl ]", verb3: "stolen", pronunciation3: "[ ˈstoʊlən ]" },
  { verb1: "stick", pronunciation1: "[ stɪk ]", verb2: "stuck", pronunciation2: "[ stʌk ]", verb3: "stuck", pronunciation3: "[ stʌk ]" },
  { verb1: "sting", pronunciation1: "[ stɪŋ ]", verb2: "stung", pronunciation2: "[ stʌŋ ]", verb3: "stung", pronunciation3: "[ stʌŋ ]" },
  { verb1: "stink", pronunciation1: "[ stɪŋk ]", verb2: "stank / stunk", pronunciation2: "[ stæŋk / stʌŋk ]", verb3: "stunk", pronunciation3: "[ stʌŋk ]" },
  { verb1: "strew", pronunciation1: "[ struː ]", verb2: "strewed", pronunciation2: "[ struːd ]", verb3: "strewn / strewed", pronunciation3: "[ struːn / struːd ]" },
  { verb1: "stride", pronunciation1: "[ straɪd ]", verb2: "strode", pronunciation2: "[ stroʊd ]", verb3: "stridden", pronunciation3: "[ ˈstrɪdn̩ ]" },
  { verb1: "strike", pronunciation1: "[ straɪk ]", verb2: "struck", pronunciation2: "[ strʌk ]", verb3: "struck", pronunciation3: "[ strʌk ]" },
  { verb1: "string", pronunciation1: "[ strɪŋ ]", verb2: "strung", pronunciation2: "[ strʌŋ ]", verb3: "strung", pronunciation3: "[ strʌŋ ]" },
  { verb1: "strive", pronunciation1: "[ straɪv ]", verb2: "strove", pronunciation2: "[ stroʊv ]", verb3: "striven", pronunciation3: "[ ˈstrɪvn̩ ]" },
  { verb1: "swear", pronunciation1: "[ swɛər ]", verb2: "swore", pronunciation2: "[ swɔːr ]", verb3: "sworn", pronunciation3: "[ swɔːrn ]" },
  { verb1: "sweep", pronunciation1: "[ swiːp ]", verb2: "swept", pronunciation2: "[ swɛpt ]", verb3: "swept", pronunciation3: "[ swɛpt ]" },
  { verb1: "swell", pronunciation1: "[ swɛl ]", verb2: "swelled", pronunciation2: "[ swɛld ]", verb3: "swollen / swelled", pronunciation3: "[ ˈswoʊlən / swɛld ]" },
  { verb1: "swim", pronunciation1: "[ swɪm ]", verb2: "swam", pronunciation2: "[ swæm ]", verb3: "swum", pronunciation3: "[ swʌm ]" },
  { verb1: "swing", pronunciation1: "[ swɪŋ ]", verb2: "swung", pronunciation2: "[ swʌŋ ]", verb3: "swung", pronunciation3: "[ swʌŋ ]" },
  // T
  // {verb1: "take", verb2: "took", verb3: "taken"},
  // {verb1: "teach", verb2: "taught", verb3: "taught"},
  // {verb1: "tear", verb2: "tore", verb3: "torn"},
  // {verb1: "tell", verb2: "told", verb3: "told"},
  // {verb1: "think", verb2: "thought", verb3: "thought"},
  // {verb1: "thrive", verb2: "throve / trived", verb3: "thriven / trived"},
  // {verb1: "throw", verb2: "threw", verb3: "thrown"},
  // {verb1: "thrust", verb2: "thrust", verb3: "thrust"},
  // {verb1: "tread", verb2: "trod", verb3: "trod / trodden"},
  { verb1: "take", pronunciation1: "[ teɪk ]", verb2: "took", pronunciation2: "[ tʊk ]", verb3: "taken", pronunciation3: "[ ˈteɪkən ]" },
  { verb1: "teach", pronunciation1: "[ tiːtʃ ]", verb2: "taught", pronunciation2: "[ tɔːt ]", verb3: "taught", pronunciation3: "[ tɔːt ]" },
  { verb1: "tear", pronunciation1: "[ tɛər ]", verb2: "tore", pronunciation2: "[ tɔːr ]", verb3: "torn", pronunciation3: "[ tɔːrn ]" },
  { verb1: "tell", pronunciation1: "[ tɛl ]", verb2: "told", pronunciation2: "[ toʊld ]", verb3: "told", pronunciation3: "[ toʊld ]" },
  { verb1: "think", pronunciation1: "[ θɪŋk ]", verb2: "thought", pronunciation2: "[ θɔːt ]", verb3: "thought", pronunciation3: "[ θɔːt ]" },
  { verb1: "thrive", pronunciation1: "[ θraɪv ]", verb2: "throve / thrived", pronunciation2: "[ θroʊv / θraɪvd ]", verb3: "thriven / thrived", pronunciation3: "[ ˈθrɪvn̩ / θraɪvd ]" },
  { verb1: "throw", pronunciation1: "[ θroʊ ]", verb2: "threw", pronunciation2: "[ θruː ]", verb3: "thrown", pronunciation3: "[ θroʊn ]" },
  { verb1: "thrust", pronunciation1: "[ θrʌst ]", verb2: "thrust", pronunciation2: "[ θrʌst ]", verb3: "thrust", pronunciation3: "[ θrʌst ]" },
  { verb1: "tread", pronunciation1: "[ trɛd ]", verb2: "trod", pronunciation2: "[ trɒd ]", verb3: "trod / trodden", pronunciation3: "[ trɒd / ˈtrɒdn̩ ]" },
  // U
  // {verb1: "undergo", verb2: "underwent", verb3: "undergone"},
  // {verb1: "underline", verb2: "underlay", verb3: "underlain"},
  // {verb1: "underpay", verb2: "underpaid", verb3: "underpaid"},
  // {verb1: "understand", verb2: "understood", verb3: "understood"},
  // {verb1: "undertake", verb2: "undertook", verb3: "undertaken"},
  // {verb1: "undo", verb2: "undid", verb3: "undone"},
  // {verb1: "unfreeze", verb2: "unfroze", verb3: "unfrozen"},
  // {verb1: "unwind", verb2: "unwound", verb3: "unwound"},
  // {verb1: "upset", verb2: "upset", verb3: "upset"},
  { verb1: "undergo", pronunciation1: "[ ˌʌndərˈɡoʊ ]", verb2: "underwent", pronunciation2: "[ ˌʌndərˈwɛnt ]", verb3: "undergone", pronunciation3: "[ ˌʌndərˈɡɔːn ]" },
  { verb1: "underline", pronunciation1: "[ ˈʌndərˌlaɪn ]", verb2: "underlay", pronunciation2: "[ ˈʌndərˌleɪ ]", verb3: "underlain", pronunciation3: "[ ˈʌndərˌleɪn ]" },
  { verb1: "underpay", pronunciation1: "[ ˌʌndərˈpeɪ ]", verb2: "underpaid", pronunciation2: "[ ˌʌndərˈpeɪd ]", verb3: "underpaid", pronunciation3: "[ ˌʌndərˈpeɪd ]" },
  { verb1: "understand", pronunciation1: "[ ˌʌndərˈstænd ]", verb2: "understood", pronunciation2: "[ ˌʌndərˈstʊd ]", verb3: "understood", pronunciation3: "[ ˌʌndərˈstʊd ]" },
  { verb1: "undertake", pronunciation1: "[ ˌʌndərˈteɪk ]", verb2: "undertook", pronunciation2: "[ ˌʌndərˈtʊk ]", verb3: "undertaken", pronunciation3: "[ ˌʌndərˈteɪkən ]" },
  { verb1: "undo", pronunciation1: "[ ˌʌnˈduː ]", verb2: "undid", pronunciation2: "[ ˌʌnˈdɪd ]", verb3: "undone", pronunciation3: "[ ˌʌnˈdʌn ]" },
  { verb1: "unfreeze", pronunciation1: "[ ˌʌnˈfriːz ]", verb2: "unfroze", pronunciation2: "[ ˌʌnˈfroʊz ]", verb3: "unfrozen", pronunciation3: "[ ˌʌnˈfroʊzn̩ ]" },
  { verb1: "unwind", pronunciation1: "[ ˌʌnˈwaɪnd ]", verb2: "unwound", pronunciation2: "[ ˌʌnˈwaʊnd ]", verb3: "unwound", pronunciation3: "[ ˌʌnˈwaʊnd ]" },
  { verb1: "upset", pronunciation1: "[ ʌpˈsɛt ]", verb2: "upset", pronunciation2: "[ ʌpˈsɛt ]", verb3: "upset", pronunciation3: "[ ʌpˈsɛt ]" },
  // W
  // {verb1: "wake", verb2: "woke / waked", verb3: "woken / waked"},
  // {verb1: "wear", verb2: "wore", verb3: "worn"},
  // {verb1: "weave", verb2: "wove / weaved", verb3: "woven / weaved"},
  // {verb1: "wed", verb2: "wed / wedded", verb3: "wed / wedded"},
  // {verb1: "weep", verb2: "wept", verb3: "wept"},
  // {verb1: "wet", verb2: "wet / wetted", verb3: "wet / wetted"},
  // {verb1: "win", verb2: "won", verb3: "won"},
  // {verb1: "withdraw", verb2: "withdrew", verb3: "withdrawn"},
  // {verb1: "withhold", verb2: "withheld", verb3: "withheld"},
  // {verb1: "withstand", verb2: "withstood", verb3: "withstood"},
  // {verb1: "wring", verb2: "wrung", verb3: "wrung"},
  // {verb1: "write", verb2: "wrote", verb3: "written"},
  { verb1: "wake", pronunciation1: "[ weɪk ]", verb2: "woke / waked", pronunciation2: "[ woʊk / weɪkt ]", verb3: "woken / waked", pronunciation3: "[ ˈwoʊkən / weɪkt ]" },
  { verb1: "wear", pronunciation1: "[ wɛər ]", verb2: "wore", pronunciation2: "[ wɔːr ]", verb3: "worn", pronunciation3: "[ wɔːrn ]" },
  { verb1: "weave", pronunciation1: "[ wiːv ]", verb2: "wove / weaved", pronunciation2: "[ woʊv / wiːvd ]", verb3: "woven / weaved", pronunciation3: "[ ˈwoʊvən / wiːvd ]" },
  { verb1: "wed", pronunciation1: "[ wɛd ]", verb2: "wed / wedded", pronunciation2: "[ wɛd / ˈwɛdɪd ]", verb3: "wed / wedded", pronunciation3: "[ wɛd / ˈwɛdɪd ]" },
  { verb1: "weep", pronunciation1: "[ wiːp ]", verb2: "wept", pronunciation2: "[ wɛpt ]", verb3: "wept", pronunciation3: "[ wɛpt ]" },
  { verb1: "wet", pronunciation1: "[ wɛt ]", verb2: "wet / wetted", pronunciation2: "[ wɛt / ˈwɛtɪd ]", verb3: "wet / wetted", pronunciation3: "[ wɛt / ˈwɛtɪd ]" },
  { verb1: "win", pronunciation1: "[ wɪn ]", verb2: "won", pronunciation2: "[ wʌn ]", verb3: "won", pronunciation3: "[ wʌn ]" },
  { verb1: "withdraw", pronunciation1: "[ wɪðˈdrɔː ]", verb2: "withdrew", pronunciation2: "[ wɪðˈdruː ]", verb3: "withdrawn", pronunciation3: "[ wɪðˈdrɔːn ]" },
  { verb1: "withhold", pronunciation1: "[ wɪðˈhoʊld ]", verb2: "withheld", pronunciation2: "[ wɪðˈhɛld ]", verb3: "withheld", pronunciation3: "[ wɪðˈhɛld ]" },
  { verb1: "withstand", pronunciation1: "[ wɪðˈstænd ]", verb2: "withstood", pronunciation2: "[ wɪðˈstʊd ]", verb3: "withstood", pronunciation3: "[ wɪðˈstʊd ]" },
  { verb1: "wring", pronunciation1: "[ rɪŋ ]", verb2: "wrung", pronunciation2: "[ rʌŋ ]", verb3: "wrung", pronunciation3: "[ rʌŋ ]" },
  { verb1: "write", pronunciation1: "[ raɪt ]", verb2: "wrote", pronunciation2: "[ roʊt ]", verb3: "written", pronunciation3: "[ ˈrɪtn̩ ]" }
]

export const cityData: Words[] = [
  {id: 1, word: "map", questionWords: ["taxi", "car", "platform", "map"], correctWord: "map", isCorrect: false, selectedAnswer: ""},
  {id: 2, word: "taxi", questionWords: ["taxi", "car", "map", "platform"], correctWord: "taxi", isCorrect: false, selectedAnswer: ""},
  {id: 3, word: "car", questionWords: ["taxi", "platform", "map", "car",], correctWord: "car", isCorrect: false, selectedAnswer: ""},
  {id: 4, word: "platform", questionWords: ["taxi", "car", "map", "platform",], correctWord: "platform", isCorrect: false, selectedAnswer: ""},
  {id: 5, word: "scooter", questionWords: ["underground", "passenger", "train", "scooter"], correctWord: "scooter", isCorrect: false, selectedAnswer: ""},
  {id: 6, word: "underground", questionWords: ["underground", "train", "scooter", "passenger",], correctWord: "underground", isCorrect: false, selectedAnswer: ""},
  {id: 7, word: "passenger", questionWords: ["train", "scooter", "underground", "passenger"], correctWord: "passenger", isCorrect: false, selectedAnswer: ""},
  {id: 8, word: "train", questionWords: ["passenger", "train", "underground", "scooter"], correctWord: "train", isCorrect: false, selectedAnswer: ""},
  {id: 9, word: "accident", questionWords: ["helicopter", "truck", "high-speed", "accident"], correctWord: "accident", isCorrect: false, selectedAnswer: ""},
  {id: 10, word: "helicopter", questionWords: ["helicopter", "accident", "truck", "high-speed",], correctWord: "helicopter", isCorrect: false, selectedAnswer: ""}
];
export const travelingData: Words[] = [
  { id: 1, word: "airport", questionWords: ["airport", "hotel", "luggage", "passport"], correctWord: "airport", isCorrect: false, selectedAnswer: "" },
  { id: 2, word: "hotel", questionWords: ["airport", "hotel", "tourist", "destination"], correctWord: "hotel", isCorrect: false, selectedAnswer: "" },
  { id: 3, word: "luggage", questionWords: ["ticket", "passport", "luggage", "tour"], correctWord: "luggage", isCorrect: false, selectedAnswer: "" },
  { id: 4, word: "passport", questionWords: ["visa", "customs", "passport", "ticket"], correctWord: "passport", isCorrect: false, selectedAnswer: "" },
  { id: 5, word: "tourist", questionWords: ["traveler", "tourist", "visitor", "guide"], correctWord: "tourist", isCorrect: false, selectedAnswer: "" },
  { id: 6, word: "destination", questionWords: ["journey", "destination", "trip", "holiday"], correctWord: "destination", isCorrect: false, selectedAnswer: "" },
  { id: 7, word: "ticket", questionWords: ["boarding", "ticket", "seat", "schedule"], correctWord: "ticket", isCorrect: false, selectedAnswer: "" },
  { id: 8, word: "visa", questionWords: ["passport", "visa", "permit", "document"], correctWord: "visa", isCorrect: false, selectedAnswer: "" },
  { id: 9, word: "guide", questionWords: ["leader", "guide", "instructor", "map"], correctWord: "guide", isCorrect: false, selectedAnswer: "" },
  { id: 10, word: "customs", questionWords: ["border", "immigration", "customs", "security"], correctWord: "customs", isCorrect: false, selectedAnswer: "" },
];
export const foodsAndDrinksData: Words[] = [
  { id: 1, word: "apple", questionWords: ["banana", "grape", "apple", "orange"], correctWord: "apple", isCorrect: false, selectedAnswer: "" },
  { id: 2, word: "bread", questionWords: ["rice", "pasta", "bread", "cereal"], correctWord: "bread", isCorrect: false, selectedAnswer: "" },
  { id: 3, word: "water", questionWords: ["juice", "soda", "water", "milk"], correctWord: "water", isCorrect: false, selectedAnswer: "" },
  { id: 4, word: "coffee", questionWords: ["tea", "coffee", "milk", "chocolate"], correctWord: "coffee", isCorrect: false, selectedAnswer: "" },
  { id: 5, word: "cheese", questionWords: ["butter", "cheese", "yogurt", "cream"], correctWord: "cheese", isCorrect: false, selectedAnswer: "" },
  { id: 6, word: "soup", questionWords: ["salad", "soup", "sandwich", "pizza"], correctWord: "soup", isCorrect: false, selectedAnswer: "" },
  { id: 7, word: "meat", questionWords: ["chicken", "fish", "meat", "vegetable"], correctWord: "meat", isCorrect: false, selectedAnswer: "" },
  { id: 8, word: "sugar", questionWords: ["salt", "pepper", "sugar", "spice"], correctWord: "sugar", isCorrect: false, selectedAnswer: "" },
  { id: 9, word: "honey", questionWords: ["jam", "honey", "syrup", "butter"], correctWord: "honey", isCorrect: false, selectedAnswer: "" },
  { id: 10, word: "vegetable", questionWords: ["fruit", "vegetable", "grain", "dairy"], correctWord: "vegetable", isCorrect: false, selectedAnswer: "" },
];
export const homeData: Words[] = [
  { id: 1, word: "sofa", questionWords: ["sofa", "table", "chair", "bed"], correctWord: "sofa", isCorrect: false, selectedAnswer: "" },
  { id: 2, word: "kitchen", questionWords: ["bathroom", "kitchen", "bedroom", "living room"], correctWord: "kitchen", isCorrect: false, selectedAnswer: "" },
  { id: 3, word: "lamp", questionWords: ["lamp", "mirror", "clock", "cushion"], correctWord: "lamp", isCorrect: false, selectedAnswer: "" },
  { id: 4, word: "carpet", questionWords: ["curtain", "carpet", "pillow", "blanket"], correctWord: "carpet", isCorrect: false, selectedAnswer: "" },
  { id: 5, word: "window", questionWords: ["door", "window", "wall", "ceiling"], correctWord: "window", isCorrect: false, selectedAnswer: "" },
  { id: 6, word: "fridge", questionWords: ["oven", "microwave", "fridge", "dishwasher"], correctWord: "fridge", isCorrect: false, selectedAnswer: "" },
  { id: 7, word: "wardrobe", questionWords: ["closet", "drawer", "wardrobe", "shelf"], correctWord: "wardrobe", isCorrect: false, selectedAnswer: "" },
  { id: 8, word: "toilet", questionWords: ["sink", "bathtub", "toilet", "shower"], correctWord: "toilet", isCorrect: false, selectedAnswer: "" },
  { id: 9, word: "fireplace", questionWords: ["chimney", "fireplace", "heater", "radiator"], correctWord: "fireplace", isCorrect: false, selectedAnswer: "" },
  { id: 10, word: "garage", questionWords: ["basement", "attic", "garage", "garden"], correctWord: "garage", isCorrect: false, selectedAnswer: "" },
];
export const peopleData: Words[] = [
  { id: 1, word: "teacher", questionWords: ["doctor", "engineer", "teacher", "artist"], correctWord: "teacher", isCorrect: false, selectedAnswer: "" },
  { id: 2, word: "doctor", questionWords: ["nurse", "doctor", "scientist", "lawyer"], correctWord: "doctor", isCorrect: false, selectedAnswer: "" },
  { id: 3, word: "student", questionWords: ["teacher", "student", "professor", "principal"], correctWord: "student", isCorrect: false, selectedAnswer: "" },
  { id: 4, word: "chef", questionWords: ["chef", "baker", "butcher", "farmer"], correctWord: "chef", isCorrect: false, selectedAnswer: "" },
  { id: 5, word: "driver", questionWords: ["pilot", "driver", "sailor", "cyclist"], correctWord: "driver", isCorrect: false, selectedAnswer: "" },
  { id: 6, word: "actor", questionWords: ["director", "writer", "actor", "dancer"], correctWord: "actor", isCorrect: false, selectedAnswer: "" },
  { id: 7, word: "musician", questionWords: ["singer", "musician", "painter", "sculptor"], correctWord: "musician", isCorrect: false, selectedAnswer: "" },
  { id: 8, word: "athlete", questionWords: ["runner", "athlete", "swimmer", "cyclist"], correctWord: "athlete", isCorrect: false, selectedAnswer: "" },
  { id: 9, word: "writer", questionWords: ["journalist", "writer", "poet", "novelist"], correctWord: "writer", isCorrect: false, selectedAnswer: "" },
  { id: 10, word: "scientist", questionWords: ["chemist", "scientist", "biologist", "physicist"], correctWord: "scientist", isCorrect: false, selectedAnswer: "" },
];
export const freeTimeActivitiesData: Words[] = [
  { id: 1, word: "reading", questionWords: ["reading", "writing", "drawing", "painting"], correctWord: "reading", isCorrect: false, selectedAnswer: "" },
  { id: 2, word: "cycling", questionWords: ["cycling", "swimming", "running", "walking"], correctWord: "cycling", isCorrect: false, selectedAnswer: "" },
  { id: 3, word: "gardening", questionWords: ["gardening", "cooking", "baking", "fishing"], correctWord: "gardening", isCorrect: false, selectedAnswer: "" },
  { id: 4, word: "playing chess", questionWords: ["playing chess", "watching TV", "surfing the internet", "listening to music"], correctWord: "playing chess", isCorrect: false, selectedAnswer: "" },
  { id: 5, word: "dancing", questionWords: ["dancing", "singing", "acting", "playing guitar"], correctWord: "dancing", isCorrect: false, selectedAnswer: "" },
  { id: 6, word: "camping", questionWords: ["camping", "hiking", "fishing", "climbing"], correctWord: "camping", isCorrect: false, selectedAnswer: "" },
  { id: 7, word: "cooking", questionWords: ["baking", "cooking", "grilling", "roasting"], correctWord: "cooking", isCorrect: false, selectedAnswer: "" },
  { id: 8, word: "shopping", questionWords: ["shopping", "watching movies", "playing video games", "reading books"], correctWord: "shopping", isCorrect: false, selectedAnswer: "" },
  { id: 9, word: "yoga", questionWords: ["meditation", "yoga", "exercise", "gymnastics"], correctWord: "yoga", isCorrect: false, selectedAnswer: "" },
  { id: 10, word: "traveling", questionWords: ["traveling", "photography", "blogging", "exploring"], correctWord: "traveling", isCorrect: false, selectedAnswer: "" },
];
export const natureData: Words[] = [
  { id: 1, word: "forest", questionWords: ["forest", "river", "mountain", "ocean"], correctWord: "forest", isCorrect: false, selectedAnswer: "" },
  { id: 2, word: "river", questionWords: ["lake", "ocean", "river", "stream"], correctWord: "river", isCorrect: false, selectedAnswer: "" },
  { id: 3, word: "mountain", questionWords: ["hill", "valley", "mountain", "cliff"], correctWord: "mountain", isCorrect: false, selectedAnswer: "" },
  { id: 4, word: "ocean", questionWords: ["sea", "ocean", "lake", "river"], correctWord: "ocean", isCorrect: false, selectedAnswer: "" },
  { id: 5, word: "desert", questionWords: ["desert", "forest", "plain", "swamp"], correctWord: "desert", isCorrect: false, selectedAnswer: "" },
  { id: 6, word: "volcano", questionWords: ["earthquake", "volcano", "hurricane", "storm"], correctWord: "volcano", isCorrect: false, selectedAnswer: "" },
  { id: 7, word: "waterfall", questionWords: ["fountain", "geyser", "waterfall", "lake"], correctWord: "waterfall", isCorrect: false, selectedAnswer: "" },
  { id: 8, word: "cave", questionWords: ["cave", "tunnel", "canyon", "valley"], correctWord: "cave", isCorrect: false, selectedAnswer: "" },
  { id: 9, word: "meadow", questionWords: ["meadow", "field", "jungle", "prairie"], correctWord: "meadow", isCorrect: false, selectedAnswer: "" },
  { id: 10, word: "island", questionWords: ["peninsula", "island", "archipelago", "coast"], correctWord: "island", isCorrect: false, selectedAnswer: "" },
];
export const languageData: Words[] = [
  { id: 1, word: "grammar", questionWords: ["vocabulary", "grammar", "pronunciation", "spelling"], correctWord: "grammar", isCorrect: false, selectedAnswer: "" },
  { id: 2, word: "vocabulary", questionWords: ["sentence", "word", "vocabulary", "phrase"], correctWord: "vocabulary", isCorrect: false, selectedAnswer: "" },
  { id: 3, word: "translation", questionWords: ["interpretation", "translation", "reading", "writing"], correctWord: "translation", isCorrect: false, selectedAnswer: "" },
  { id: 4, word: "pronunciation", questionWords: ["accent", "pronunciation", "dialect", "speech"], correctWord: "pronunciation", isCorrect: false, selectedAnswer: "" },
  { id: 5, word: "synonym", questionWords: ["synonym", "antonym", "homonym", "metaphor"], correctWord: "synonym", isCorrect: false, selectedAnswer: "" },
  { id: 6, word: "idiom", questionWords: ["phrase", "idiom", "proverb", "expression"], correctWord: "idiom", isCorrect: false, selectedAnswer: "" },
  { id: 7, word: "sentence", questionWords: ["clause", "sentence", "paragraph", "essay"], correctWord: "sentence", isCorrect: false, selectedAnswer: "" },
  { id: 8, word: "phonetics", questionWords: ["grammar", "phonetics", "semantics", "syntax"], correctWord: "phonetics", isCorrect: false, selectedAnswer: "" },
  { id: 9, word: "dialect", questionWords: ["dialect", "accent", "language", "speech"], correctWord: "dialect", isCorrect: false, selectedAnswer: "" },
  { id: 10, word: "spelling", questionWords: ["spelling", "pronunciation", "reading", "writing"], correctWord: "spelling", isCorrect: false, selectedAnswer: "" },
];
export const technologyData: Words[] = [
  { id: 1, word: "computer", questionWords: ["laptop", "desktop", "computer", "tablet"], correctWord: "computer", isCorrect: false, selectedAnswer: "" },
  { id: 2, word: "internet", questionWords: ["wifi", "internet", "network", "router"], correctWord: "internet", isCorrect: false, selectedAnswer: "" },
  { id: 3, word: "software", questionWords: ["hardware", "application", "software", "program"], correctWord: "software", isCorrect: false, selectedAnswer: "" },
  { id: 4, word: "robot", questionWords: ["AI", "robot", "machine", "automation"], correctWord: "robot", isCorrect: false, selectedAnswer: "" },
  { id: 5, word: "cybersecurity", questionWords: ["cybersecurity", "encryption", "hacking", "password"], correctWord: "cybersecurity", isCorrect: false, selectedAnswer: "" },
  { id: 6, word: "database", questionWords: ["storage", "database", "server", "cloud"], correctWord: "database", isCorrect: false, selectedAnswer: "" },
  { id: 7, word: "artificial intelligence", questionWords: ["AI", "machine learning", "artificial intelligence", "robotics"], correctWord: "artificial intelligence", isCorrect: false, selectedAnswer: "" },
  { id: 8, word: "algorithm", questionWords: ["function", "algorithm", "equation", "calculation"], correctWord: "algorithm", isCorrect: false, selectedAnswer: "" },
  { id: 9, word: "cloud computing", questionWords: ["hosting", "cloud computing", "networking", "server"], correctWord: "cloud computing", isCorrect: false, selectedAnswer: "" },
  { id: 10, word: "virtual reality", questionWords: ["augmented reality", "simulation", "virtual reality", "game"], correctWord: "virtual reality", isCorrect: false, selectedAnswer: "" },
];
export const educationData: Words[] = [
  { id: 1, word: "school", questionWords: ["college", "university", "school", "academy"], correctWord: "school", isCorrect: false, selectedAnswer: "" },
  { id: 2, word: "teacher", questionWords: ["professor", "instructor", "lecturer", "teacher"], correctWord: "teacher", isCorrect: false, selectedAnswer: "" },
  { id: 3, word: "homework", questionWords: ["assignment", "homework", "project", "task"], correctWord: "homework", isCorrect: false, selectedAnswer: "" },
  { id: 4, word: "lecture", questionWords: ["lecture", "seminar", "presentation", "workshop"], correctWord: "lecture", isCorrect: false, selectedAnswer: "" },
  { id: 5, word: "exam", questionWords: ["test", "exam", "quiz", "assessment"], correctWord: "exam", isCorrect: false, selectedAnswer: "" },
  { id: 6, word: "library", questionWords: ["library", "bookstore", "reading room", "archives"], correctWord: "library", isCorrect: false, selectedAnswer: "" },
  { id: 7, word: "curriculum", questionWords: ["curriculum", "syllabus", "course", "program"], correctWord: "curriculum", isCorrect: false, selectedAnswer: "" },
  { id: 8, word: "degree", questionWords: ["certificate", "degree", "diploma", "qualification"], correctWord: "degree", isCorrect: false, selectedAnswer: "" },
  { id: 9, word: "scholarship", questionWords: ["grant", "scholarship", "loan", "funding"], correctWord: "scholarship", isCorrect: false, selectedAnswer: "" },
  { id: 10, word: "university", questionWords: ["college", "university", "institute", "academy"], correctWord: "university", isCorrect: false, selectedAnswer: "" },
];
export const fashionData: Words[] = [
  { id: 1, word: "dress", questionWords: ["shirt", "pants", "dress", "skirt"], correctWord: "dress", isCorrect: false, selectedAnswer: "" },
  { id: 2, word: "sneakers", questionWords: ["boots", "sandals", "sneakers", "heels"], correctWord: "sneakers", isCorrect: false, selectedAnswer: "" },
  { id: 3, word: "jewelry", questionWords: ["scarf", "hat", "jewelry", "belt"], correctWord: "jewelry", isCorrect: false, selectedAnswer: "" },
  { id: 4, word: "fashion", questionWords: ["style", "trend", "fashion", "design"], correctWord: "fashion", isCorrect: false, selectedAnswer: "" },
  { id: 5, word: "model", questionWords: ["designer", "stylist", "model", "tailor"], correctWord: "model", isCorrect: false, selectedAnswer: "" },
  { id: 6, word: "runway", questionWords: ["stage", "catwalk", "runway", "hall"], correctWord: "runway", isCorrect: false, selectedAnswer: "" },
  { id: 7, word: "boutique", questionWords: ["mall", "shop", "boutique", "market"], correctWord: "boutique", isCorrect: false, selectedAnswer: "" },
  { id: 8, word: "tailor", questionWords: ["seamstress", "tailor", "designer", "stylist"], correctWord: "tailor", isCorrect: false, selectedAnswer: "" },
  { id: 9, word: "trend", questionWords: ["vogue", "trend", "style", "fashion"], correctWord: "trend", isCorrect: false, selectedAnswer: "" },
  { id: 10, word: "accessory", questionWords: ["clothes", "shoes", "accessory", "jewelry"], correctWord: "accessory", isCorrect: false, selectedAnswer: "" },
];
export const artEntertainmentData: Words[] = [
  { id: 1, word: "painting", questionWords: ["drawing", "sculpture", "painting", "photography"], correctWord: "painting", isCorrect: false, selectedAnswer: "" },
  { id: 2, word: "theater", questionWords: ["cinema", "theater", "concert", "exhibition"], correctWord: "theater", isCorrect: false, selectedAnswer: "" },
  { id: 3, word: "artist", questionWords: ["painter", "musician", "artist", "writer"], correctWord: "artist", isCorrect: false, selectedAnswer: "" },
  { id: 4, word: "sculpture", questionWords: ["statue", "sculpture", "drawing", "collage"], correctWord: "sculpture", isCorrect: false, selectedAnswer: "" },
  { id: 5, word: "cinema", questionWords: ["film", "cinema", "show", "opera"], correctWord: "cinema", isCorrect: false, selectedAnswer: "" },
  { id: 6, word: "music", questionWords: ["dance", "song", "music", "instrument"], correctWord: "music", isCorrect: false, selectedAnswer: "" },
  { id: 7, word: "director", questionWords: ["actor", "director", "writer", "producer"], correctWord: "director", isCorrect: false, selectedAnswer: "" },
  { id: 8, word: "gallery", questionWords: ["museum", "gallery", "library", "studio"], correctWord: "gallery", isCorrect: false, selectedAnswer: "" },
  { id: 9, word: "opera", questionWords: ["ballet", "opera", "drama", "musical"], correctWord: "opera", isCorrect: false, selectedAnswer: "" },
  { id: 10, word: "festival", questionWords: ["carnival", "festival", "event", "parade"], correctWord: "festival", isCorrect: false, selectedAnswer: "" },
];
export const healthData: Words[] = [
  { id: 1, word: "doctor", questionWords: ["doctor", "nurse", "patient", "surgeon"], correctWord: "doctor", isCorrect: false, selectedAnswer: "" },
  { id: 2, word: "exercise", questionWords: ["diet", "exercise", "meditation", "yoga"], correctWord: "exercise", isCorrect: false, selectedAnswer: "" },
  { id: 3, word: "nutrition", questionWords: ["food", "nutrition", "diet", "calories"], correctWord: "nutrition", isCorrect: false, selectedAnswer: "" },
  { id: 4, word: "hospital", questionWords: ["clinic", "hospital", "pharmacy", "emergency"], correctWord: "hospital", isCorrect: false, selectedAnswer: "" },
  { id: 5, word: "medicine", questionWords: ["pill", "medicine", "vitamin", "drug"], correctWord: "medicine", isCorrect: false, selectedAnswer: "" },
  { id: 6, word: "therapy", questionWords: ["treatment", "therapy", "surgery", "massage"], correctWord: "therapy", isCorrect: false, selectedAnswer: "" },
  { id: 7, word: "vaccination", questionWords: ["medication", "vaccination", "prescription", "injection"], correctWord: "vaccination", isCorrect: false, selectedAnswer: "" },
  { id: 8, word: "mental health", questionWords: ["physical health", "mental health", "well-being", "fitness"], correctWord: "mental health", isCorrect: false, selectedAnswer: "" },
  { id: 9, word: "emergency", questionWords: ["accident", "emergency", "trauma", "first aid"], correctWord: "emergency", isCorrect: false, selectedAnswer: "" },
  { id: 10, word: "dentist", questionWords: ["orthodontist", "dentist", "surgeon", "pediatrician"], correctWord: "dentist", isCorrect: false, selectedAnswer: "" },
];
export const careerData: Words[] = [
  { id: 1, word: "resume", questionWords: ["application", "resume", "interview", "portfolio"], correctWord: "resume", isCorrect: false, selectedAnswer: "" },
  { id: 2, word: "interview", questionWords: ["meeting", "conference", "interview", "discussion"], correctWord: "interview", isCorrect: false, selectedAnswer: "" },
  { id: 3, word: "promotion", questionWords: ["bonus", "salary", "promotion", "raise"], correctWord: "promotion", isCorrect: false, selectedAnswer: "" },
  { id: 4, word: "manager", questionWords: ["employee", "supervisor", "manager", "boss"], correctWord: "manager", isCorrect: false, selectedAnswer: "" },
  { id: 5, word: "salary", questionWords: ["income", "salary", "wage", "earnings"], correctWord: "salary", isCorrect: false, selectedAnswer: "" },
  { id: 6, word: "internship", questionWords: ["training", "internship", "volunteering", "job"], correctWord: "internship", isCorrect: false, selectedAnswer: "" },
  { id: 7, word: "entrepreneur", questionWords: ["businessman", "entrepreneur", "investor", "executive"], correctWord: "entrepreneur", isCorrect: false, selectedAnswer: "" },
  { id: 8, word: "networking", questionWords: ["socializing", "networking", "collaborating", "partnership"], correctWord: "networking", isCorrect: false, selectedAnswer: "" },
  { id: 9, word: "leadership", questionWords: ["management", "leadership", "authority", "control"], correctWord: "leadership", isCorrect: false, selectedAnswer: "" },
  { id: 10, word: "freelance", questionWords: ["contractor", "freelance", "full-time", "part-time"], correctWord: "freelance", isCorrect: false, selectedAnswer: "" },
];

export const categories: CategoryT[] = [
  {id: "1", title: "Traveling", words: travelingData, img: traveling,},
  {id: "2", title: "Foods and Drinks", words: foodsAndDrinksData, img: foods,},
  {id: "3", title: "City", words: cityData, img: city,},
  {id: "4", title: "Home", words: homeData, img: home,},
  {id: "5", title: "People", words: peopleData, img: people,},
  {id: "6", title: "Free time Activities", words: freeTimeActivitiesData, img: freeTime,},
  {id: "7", title: "Nature", words: natureData, img: nature},
  {id: "8", title: "Language", words: languageData, img: language,},
  {id: "9", title: "Technology", words: technologyData, img: technology,},
  {id: "10", title: "Education", words: educationData, img: education,},
  {id: "11", title: "Fashion", words: fashionData, img: fashion,},
  {id: "12", title: "Art", words: artEntertainmentData, img: art,},
  {id: "13", title: "Health", words: healthData, img: health,},
  {id: "14", title: "Career", words: careerData, img: career,},
]
